language: python
python: 3.5
dist: trusty
services: docker
filter_secrets: false
os: linux

cache:
  ccache: true
  directories:
  - $HOME/.ccache
  - $HOME/.cache/pip

env:
  global:
  - REPO_DIR=Fiona
  - BUILD_COMMIT=1.8.18
 

addons:
  artifacts:
    paths:
    - $(ls wheelhouse/*.whl)

jobs:
  include:
  - name: "Python 2.7 x86_64 and linux"
    os: linux
    env:
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - USE_CCACHE=1
    - MB_PYTHON_VERSION=2.7
    - NP_BUILD_DEP=numpy==1.10.4
    - NP_TEST_DEP=numpy==1.11.3
  - name: "Python 3.5 x86_64 linux"
    os: linux
    env:
    - UNICODE_WIDTH=32
    - USE_CCACHE=1
    - MB_PYTHON_VERSION=3.5
    - NP_BUILD_DEP=numpy==1.14.5
    - NP_TEST_DEP=numpy==1.14.5
  - name: "Python 3.6 x86_64 linux"
    os: linux
    env:
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - USE_CCACHE=1
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP=numpy==1.14.5
    - NP_TEST_DEP=numpy==1.14.5
  - name: "Python 3.6 aarch64 linux"
    arch: arm64
    os: linux
    env:
    - PLAT=aarch64
    - MB_ML_VER=2014
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP=numpy==1.20.3
    - NP_TEST_DEP=numpy==1.20.3
  - name: "Python 3.7 x86_64 linux"
    os: linux
    env:
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - USE_CCACHE=1
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.14.5
    - NP_TEST_DEP=numpy==1.14.5
  - name: "Python 3.7 aarch64 linux"
    arch: arm64
    os: linux
    env:
    - PLAT=aarch64
    - MB_ML_VER=2014
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.20.3
    - NP_TEST_DEP=numpy==1.20.3
  - name: "Python 3.8 x86_64 linux"
    os: linux
    env:
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - USE_CCACHE=1
    - MB_PYTHON_VERSION=3.8
    - NP_BUILD_DEP=numpy==1.17.3
    - NP_TEST_DEP=numpy==1.17.3
  - name: "Python 3.8 aarch64 linux"
    arch: arm64
    os: linux
    env:
    - PLAT=aarch64
    - MB_ML_VER=2014
    - MB_PYTHON_VERSION=3.8
    - NP_BUILD_DEP=numpy==1.20.3
    - NP_TEST_DEP=numpy==1.20.3
  - name: "Python 3.5 osx"
    os: osx
    language: generic
    env:
    - UNICODE_WIDTH=32
    - USE_CCACHE=1
    - MB_PYTHON_VERSION=3.5
    - NP_BUILD_DEP=numpy==1.14.5
    - NP_TEST_DEP=numpy==1.14.5
  - name: "Python 3.6 osx"
    os: osx
    language: generic
    env:
    - UNICODE_WIDTH=32
    - USE_CCACHE=1
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP=numpy==1.14.5
    - NP_TEST_DEP=numpy==1.14.5
  - name: "Python 3.7 osx"
    os: osx
    language: generic
    env:
    - UNICODE_WIDTH=32
    - USE_CCACHE=1
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.14.5
    - NP_TEST_DEP=numpy==1.14.5
  - os: osx
    language: generic
    osx_image: xcode10.1
    env:
    - UNICODE_WIDTH=32
    - USE_CCACHE=1
    - MB_PYTHON_VERSION=3.8
    - NP_BUILD_DEP=numpy==1.17.3
    - NP_TEST_DEP=numpy==1.17.3
    - MB_PYTHON_OSX_VER=10.9

before_install:
    - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
    - BUILD_DEPENDS="$NP_BUILD_DEP cython wheel"
    - TEST_DEPENDS="$NP_TEST_DEP attrs==19.1.0 pytest==4.0.2 mock;python_version<'3.4' boto3 packaging hypothesis==4.38.1 wheel==0.34.2 pytz $GEN_DEPS"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT
    - ls -l ${TRAVIS_BUILD_DIR}/wheelhouse/
    - unzip -l ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl

script:
    - install_run $PLAT
